"use client";
import { useMemo, useState } from "react";

type Inputs={market:number;migration:number;premium:number;normalLoss:number;investmentYield:number;operatingCost:number;reinsuranceCost:number;initialCapital:number;crisisYear:number;crisisYears:number;crisisLoss:number;bankFirstLoss:number;reinsuranceShare:number};
const initial:Inputs={market:400,migration:10,premium:.2025,normalLoss:.02,investmentYield:4.5,operatingCost:8,reinsuranceCost:.025,initialCapital:300,crisisYear:5,crisisYears:1,crisisLoss:2,bankFirstLoss:25,reinsuranceShare:50};
const fmt=(n:number,d=0)=>new Intl.NumberFormat("en-NZ",{maximumFractionDigits:d}).format(n);
function Slider({label,value,min,max,step,suffix,onChange}:{label:string;value:number;min:number;max:number;step:number;suffix:string;onChange:(n:number)=>void}){return <label className="control"><span><b>{label}</b><output>{fmt(value,step<1?3:0)}{suffix}</output></span><input aria-label={label} type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>}

export default function Home(){
 const[v,setV]=useState(initial); const set=(key:keyof Inputs)=>(value:number)=>setV(o=>({...o,[key]:value}));
 const result=useMemo(()=>{let reserve=v.initialCapital,crownDraw=0,totalPremium=0,totalClaims=0,totalBankLoss=0,totalReinsurance=0;const rows=[];for(let year=1;year<=10;year++){const pool=Math.min(v.market,v.market*(v.migration/100)*year);const premium=pool*1000*(v.premium/100);const reCost=pool*1000*(v.reinsuranceCost/100);const investment=Math.max(0,reserve)*(v.investmentYield/100);const isCrisis=year>=v.crisisYear&&year<v.crisisYear+v.crisisYears;const grossLoss=pool*1000*((isCrisis?v.crisisLoss:v.normalLoss)/100);const bankLoss=grossLoss*(v.bankFirstLoss/100);const remaining=grossLoss-bankLoss;const reinsurance=isCrisis?remaining*(v.reinsuranceShare/100):0;const claim=remaining-reinsurance;let closing=reserve+premium+investment-claim-reCost-v.operatingCost;let draw=0;if(closing<0){draw=-closing;crownDraw+=draw;closing=0}totalPremium+=premium;totalClaims+=claim;totalBankLoss+=bankLoss;totalReinsurance+=reinsurance;reserve=closing;rows.push({year,pool,premium,claim,bankLoss,reinsurance,reserve,draw,isCrisis})}return{rows,reserve,crownDraw,totalPremium,totalClaims,totalBankLoss,totalReinsurance}},[v]);
 const maxBar=Math.max(...result.rows.map(r=>r.reserve),1);const crisisGross=result.rows.filter(r=>r.isCrisis).reduce((s,r)=>s+r.claim+r.bankLoss+r.reinsurance,0);const lossTotal=Math.max(1,result.totalClaims+result.totalBankLoss+result.totalReinsurance);
 return <main>
  <header className="topbar"><div className="brand"><span className="mark">NZ</span><span>Economic Stress Lab</span></div><div className="status"><i/>Working model · v0.1</div></header>
  <section className="intro"><div><p className="eyebrow">MORTGAGE SYSTEM STRESS TEST · 2026–2036</p><h1>Who absorbs the loss<br/>when housing breaks?</h1></div><p className="lede">An open scenario model comparing lender first-loss, national mortgage insurance, international reinsurance and the Crown backstop. Change the assumptions. Try to kill the proposal.</p></section>
  <section className="workspace">
   <aside className="panel controls"><div className="panelTitle"><span>Scenario inputs</span><button onClick={()=>setV(initial)}>Reset</button></div>
    <h3>Market & programme</h3><Slider label="Mortgage market" value={v.market} min={200} max={600} step={10} suffix="bn" onChange={set("market")}/><Slider label="Annual migration" value={v.migration} min={2} max={25} step={1} suffix="%" onChange={set("migration")}/><Slider label="Average premium" value={v.premium} min={.05} max={.6} step={.0025} suffix="%" onChange={set("premium")}/><Slider label="Initial Crown capital" value={v.initialCapital} min={0} max={2000} step={50} suffix="m" onChange={set("initialCapital")}/>
    <h3>Cost & normal years</h3><Slider label="Normal insured loss" value={v.normalLoss} min={0} max={.2} step={.005} suffix="%" onChange={set("normalLoss")}/><Slider label="Reinsurance premium" value={v.reinsuranceCost} min={0} max={.2} step={.005} suffix="%" onChange={set("reinsuranceCost")}/><Slider label="Annual operating cost" value={v.operatingCost} min={0} max={50} step={1} suffix="m" onChange={set("operatingCost")}/><Slider label="Reserve yield" value={v.investmentYield} min={0} max={7} step={.25} suffix="%" onChange={set("investmentYield")}/>
    <h3>Crisis</h3><Slider label="Crisis starts" value={v.crisisYear} min={1} max={10} step={1} suffix=" yr" onChange={set("crisisYear")}/><Slider label="Crisis duration" value={v.crisisYears} min={1} max={3} step={1} suffix=" yr" onChange={set("crisisYears")}/><Slider label="Gross mortgage loss" value={v.crisisLoss} min={.5} max={8} step={.25} suffix="%" onChange={set("crisisLoss")}/><Slider label="Lender first-loss" value={v.bankFirstLoss} min={0} max={60} step={5} suffix="%" onChange={set("bankFirstLoss")}/><Slider label="Reinsured remainder" value={v.reinsuranceShare} min={0} max={80} step={5} suffix="%" onChange={set("reinsuranceShare")}/>
   </aside>
   <div className="results">
    <div className="cards"><article><span>Year 10 reserve</span><strong>${fmt(result.reserve)}m</strong><small>{(result.reserve/(v.market*1000)*100).toFixed(2)}% of market</small></article><article className={result.crownDraw>0?"warn":"good"}><span>Crown liquidity required</span><strong>${fmt(result.crownDraw)}m</strong><small>{result.crownDraw>0?"programme breaches its reserve":"reserve remains solvent"}</small></article><article><span>Gross crisis loss</span><strong>${fmt(crisisGross)}m</strong><small>scenario assumption</small></article><article><span>Premiums collected</span><strong>${fmt(result.totalPremium)}m</strong><small>before programme costs</small></article></div>
    <section className="panel chartPanel"><div className="panelTitle"><span>Reserve path</span><span className="legend"><i/> closing reserve <em/> crisis</span></div><div className="chart">{result.rows.map(r=><div className="barCol" key={r.year}><div className={`bar ${r.isCrisis?"crisis":""}`} style={{height:`${Math.max(2,r.reserve/maxBar*100)}%`}}><span>${fmt(r.reserve)}m</span></div><b>Y{r.year}</b></div>)}</div></section>
    <section className="split"><article className="panel waterfall"><div className="panelTitle"><span>Loss allocation · all 10 years</span></div><div className="wfRow"><span>Lenders</span><b>${fmt(result.totalBankLoss)}m</b><i style={{width:`${result.totalBankLoss/lossTotal*100}%`}}/></div><div className="wfRow"><span>Reinsurers</span><b>${fmt(result.totalReinsurance)}m</b><i style={{width:`${result.totalReinsurance/lossTotal*100}%`}}/></div><div className="wfRow"><span>National insurer</span><b>${fmt(result.totalClaims)}m</b><i style={{width:`${result.totalClaims/lossTotal*100}%`}}/></div><div className="wfRow crown"><span>Crown facility</span><b>${fmt(result.crownDraw)}m</b><i style={{width:`${Math.min(100,result.crownDraw/Math.max(1,result.totalClaims)*100)}%`}}/></div></article>
     <article className="panel verdict"><div className="panelTitle"><span>Model verdict</span></div><strong>{result.crownDraw===0?"The funded reserve survives this scenario.":"The programme needs a Crown liquidity facility."}</strong><p>{result.crownDraw===0?"Under these assumptions, premiums, starting capital and reinsurance absorb the insured layer without an emergency draw. This is not proof of actuarial adequacy.":`The reserve is exhausted and requires $${fmt(result.crownDraw)}m. Test a higher premium, more initial capital, a larger lender share—or price the Crown facility explicitly.`}</p><div className="tag">SCENARIO, NOT FORECAST</div></article></section>
    <section className="panel tablePanel"><div className="panelTitle"><span>Annual ledger · NZD millions</span></div><div className="tableWrap"><table><thead><tr><th>Year</th><th>Pool $bn</th><th>Premium</th><th>Insurer claims</th><th>Reinsurance</th><th>Crown draw</th><th>Reserve</th></tr></thead><tbody>{result.rows.map(r=><tr key={r.year} className={r.isCrisis?"crisisRow":""}><td>Y{r.year}{r.isCrisis&&" · CRISIS"}</td><td>{fmt(r.pool,1)}</td><td>{fmt(r.premium,1)}</td><td>{fmt(r.claim,1)}</td><td>{fmt(r.reinsurance,1)}</td><td>{fmt(r.draw,1)}</td><td><b>{fmt(r.reserve,1)}</b></td></tr>)}</tbody></table></div></section>
   </div>
  </section>
  <section className="sources"><div><p className="eyebrow">DATA LAYER</p><h2>Official data where available.<br/>Assumptions where it is not.</h2></div><div className="sourceGrid"><a href="https://www.rbnz.govt.nz/statistics/" target="_blank"><b>RBNZ Statistics</b><span>Mortgage stock, lending, rates, bank and insurer balance sheets</span></a><a href="https://portal.apis.stats.govt.nz/" target="_blank"><b>Stats NZ API</b><span>Employment, population, construction, prices and national accounts</span></a><a href="https://www.treasury.govt.nz/publications/budgets/forecasts" target="_blank"><b>Treasury forecasts</b><span>Fiscal baseline, debt, unemployment and economic scenarios</span></a><div><b>Model assumptions</b><span>Premiums, PD/LGD, loss layers and reinsurance pricing remain user-controlled until independently calibrated</span></div></div></section>
  <footer><span>NZ Economic Stress Lab</span><p>Built to test a hypothesis—not to sell a conclusion.</p></footer>
 </main>
}
